[package]
name = "soft"
version = "0.1.0"
edition = "2021"

[dependencies]
auto_ops = "*"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["gfx", "bundled"]

[profile.release]
debug = true
opt-level = 3